# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobble < Formula
  desc "A super-fast, easy-to-use file downloader written in Go"
  homepage "https://github.com/shrobon/gobble"
  version "0.1.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shrobon/gobble/releases/download/v0.1.10/gobble_0.1.10_darwin_amd64.tar.gz"
      sha256 "ef03376d910cfcf5fa40c9dd0d3882fabe1e62554cdbc1585f8dbdf86ede4206"

      def install
        bin.install "gobble"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shrobon/gobble/releases/download/v0.1.10/gobble_0.1.10_darwin_arm64.tar.gz"
      sha256 "43a60e65e9c6f4ce8c1885d11e01dac461d6846dc588c4044e66a4c4681d3081"

      def install
        bin.install "gobble"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shrobon/gobble/releases/download/v0.1.10/gobble_0.1.10_linux_amd64.tar.gz"
      sha256 "bc5d5c9376af49b52c9bf983010ad1660fff2d7b7fa518c6fdc3d26bb2d12fd7"
      def install
        bin.install "gobble"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shrobon/gobble/releases/download/v0.1.10/gobble_0.1.10_linux_arm64.tar.gz"
      sha256 "d5f0afbd5bf6cbafaa34d0da2aa819754e1a1c485cb3982b3584cd3f8e788068"
      def install
        bin.install "gobble"
      end
    end
  end

  test do
    system "#{bin}/gobble", "--help"
  end
end
