# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobble < Formula
  desc "A super-fast, easy-to-use file downloader written in Go"
  homepage "https://github.com/shrobon/gobble"
  version "0.1.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shrobon/gobble/releases/download/v0.1.6/gobble_0.1.6_darwin_amd64.tar.gz"
      sha256 "032cfa47e8bb78181eb0aaa71a6cb90326a3d0eeee134819e5edd00787529f6d"

      def install
        bin.install "gobble"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shrobon/gobble/releases/download/v0.1.6/gobble_0.1.6_darwin_arm64.tar.gz"
      sha256 "b205018633b6ba0ba78d4c5aab143c70fdf9de7ca9991bf04d54e656bd4c5ddf"

      def install
        bin.install "gobble"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shrobon/gobble/releases/download/v0.1.6/gobble_0.1.6_linux_amd64.tar.gz"
      sha256 "b88398fdb74be2ca840c3005879ddf8289ddb8c69a75ba7380f9fba7ca737dd6"
      def install
        bin.install "gobble"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shrobon/gobble/releases/download/v0.1.6/gobble_0.1.6_linux_arm64.tar.gz"
      sha256 "6c356cd88e19054449bc208fbb4472211e43a1b836717150b14e083e69c1f759"
      def install
        bin.install "gobble"
      end
    end
  end

  test do
    system "#{bin}/gobble", "--help"
  end
end
